Fix comments in Dockerfile.simple
The instructions about how to use Dockerfile.simple should be
updated, because we can't build the docker binary under the
`/usr/src/docker` in the image, because it doesn't have `.git`, it
will has following error
```
error: .git directory missing and DOCKER_GITCOMMIT not specified
  Please either build with the .git directory accessible, or specify the
  exact (--short) commit hash you are building using DOCKER_GITCOMMIT for
  future accountability in diagnosing build issues.  Thanks!

```
The `.git` is in the `.dockerigore`, so there is no `.git` under `/usr/src/docker`.

So to use Dockerfile.simple to build docker binary, we need bind mount the docker
source directory to the `/usr/src/docker`

Signed-off-by: Lei Jitang <leijitang@outlook.com>